### ISSUE TITLE
TODO (8/26/22)

### ISSUE THREAD

**Issue by BradRyan** [kiftlife/kift_subgraph#1]
- [ ] P0 - Get subgraph deployed for kiftables contract using subgraph studio
- [ ] P1 - What does deploying updates on subgraph studio
- [ ] P1 - Dev environments? How can we clean this up?
- [ ] P2 - Once perks contract is deployed, try adding a new contract source
- [ ] P3 - Look into unit tests (https://thegraph.com/docs/en/developing/unit-testing-framework/)
